name: Pull Request Workflow
on:
  pull_request:
    branches: [ main ]
jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '16.x'
     - name: Install modules
       run: yarn
     - name: Lint code
       run: yarn rw lint
     - name: Build API
       run: yarn rw build api
     - name: Build web
       run: yarn rw build web

