name: Pull Request Workflow
on:
  pull_request:
    branches: [ main ]
jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '16.x'
     - name: Install modules
       run: yarn
     - name: Type-check
       run: yarn rw type-check
     - name: Lint code
       run: yarn rw lint
     - name: Build API
       run: yarn rw build api
     - name: Build web
       run: yarn rw build web

  api-unit-tests:
    runs-on: ubuntu-latest
    container: node:19-slim
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.1-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: yarn

      - name: Run API Unit Tests
        run: yarn rw test api --no-watch
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

  web-unit-tests:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '16.x'
     - name: Install modules
       run: yarn
     - name: Run Web Unit Tests
       run: yarn rw test web --no-watch


